language: node_js
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: VAlfz62Qvk5XI1YjyWo7LviQ3IrcT7HmGqBquLX8Ai9LnFD/xnmfo3qznXHnCmJSu5kBur8860rDpbpV803RAlfHkxSsx2gBqHn7+mA4Uqig7Q/kDmXZCiMCmKAxsswju/78yf1QGkT8lRVI6cztgPTmL8rLFGqFMaEKItMTop3Vrvtijqwzm04nPLEKGQI8ZaTSBlq4G5BLoBqciKTcgQXvUkl4tat6kRyrBAjkwZ298kY8qCxM3HJzmXSz+ypxSm4kArGFE1BjAzDnCAn19f78f3Iq40vnuxTRUGefAnr7FeA3OfI/zfut52orP8xW798c2he//4fV7kC6rvmk0yrmlyKxnYNElzABzfdhYrlAZNey5HSSpjCvw0Pdx000cfFcpm2A/xI6skbBlCBUNwu1i1dMD8SKZZ8J3vRKMO5TtIlXBKYYgekBTGUV0ZZZ4JTeInEigDIOXSRWrMURkFHkP5G1On1ys5PUZogzt7j40MpJDLcEUFjSQkas1Gg0NPj2P6LhOSPnVEgnFN6JDiH0F9BhdvPMCKyNy/0/RJknvsW0D+65lh2/vz4Kr1ExDN4daWmvGd2mH/Sx47SBtz6XGByhxetrgHKTPYA4Wy0SfegLkSAkni8cEOIsHUl+RiSmDUYbYnEzmkXP2mT4luXe20bzmn8tAGwyrcL6aQs=
